#!/bin/bash

serial=$1

size=${#serial}
if [ "$size" -ne "12" ] 
then
    echo "bad serial"
    exit 5
fi

s1=${serial:0:2}
s2=${serial:2:2}
s3=${serial:4:2}
s4=${serial:6:2}
s5=${serial:8:2}
s6=${serial:10:2}

#printf \\x$s1\\x$s2\\x$s3\\x$s4 > serial
printf \\x$s1\\x$s2\\x$s3\\x$s4\\x$s5\\x$s6 > serial

# take off last newline char from serial
#printf %s "$(cat serial)" > serial

if [ "$2" == "compile" ]
then
	make release
	res=0
	if [ "$res" -ne "0" ]
	then
		echo "BAD MAKE"
		exit 5
	fi
fi


srec_cat ../s110_nrf51822_7.3.0_softdevice.hex -intel _build/bunchie_buttons_s110_xxaa.bin -binary -offset 0x16000 serial -binary -offset 0x10001080 -o combined.hex -intel

cp combined.hex ../../

cd ../..
./flash.sh
